### PR TITLE
Avoid rendering issues in Airline

### LINKED ISSUE #63: Airline Tabline Redraw Bug?
I'm not sure who is responsible but only manifests after Goyo command, may require upstream fix in airline or even a vim redraw bug?

Test: Use :Goyo twice, then you'll see a graphical bug on separators of the tabline. I.e. where the > separates colors. Then put hack into config & it won't reproduce.

Test config to reproduce:
```vim
let g:win_shell = (has('win32') || has('win64')) && &shellcmdflag =~ '/'
let g:cygwin_shell = has('win32unix')
let g:vim_dir = g:win_shell ? '$HOME/vimfiles' : '$HOME/.vim'

try
  call plug#begin(expand(g:vim_dir . '/bundle'))

  Plug 'bling/vim-airline'
  Plug 'junegunn/goyo.vim'
  Plug 'tomasr/molokai'
  
  call plug#end()
catch
  echomsg 'Run command `Bootstrap`. After restart run command `pi'
endtry

let g:airline#extensions#syntastic#enabled = 1

let g:airline#extensions#tabline#enabled = 1

let g:airline_powerline_fonts = 1

let &statusline  = '%<%1* %t%m %y || %{&fenc?&fenc:&enc}[%{&ff}] ' 
let &statusline .= '%= %b(0x%B) || buf: %n || %p%% %l,%c %0*'
set laststatus=2

syntax off
set background=dark
colorscheme molokai
syntax on
```

Hack that resolves problem:
```vim
function s:goyo_leave()
  split
  redraw
  quit
endfunction

autocmd! User GoyoLeave
autocmd  User GoyoLeave nested call <SID>goyo_leave()
```

### PR DESCRIPTION
**Pull request by thirtythreeforty**
Closes #63.

Note that this is a bit of a workaround (although a very simple one) rather than a true fix, and I would understand perfectly if you didn't want to merge this.

### CODE REVIEW

**Comment by junegunn** [comment]
Thanks, I don't use airline, so I haven't checked if the fix works, but it looks harmless. But is it possible that it's a bug of airline that should be fixed?

**Comment by thirtythreeforty** [comment]
I'm not sure, honestly.  I've looked at the Airline code (the tabline rabbit hole of function calls starts [here](https://github.com/bling/vim-airline/blob/8aad42644c949e062d012c18ec2ce5934f4eced1/autoload/airline/extensions/tabline.vim#L37)), but it looks harmless enough.  Possibly it is a Vim bug.

**Comment by junegunn** [comment]
Hmm, it sure looks like a bug of airline, but considering that bling is no longer actively maintaining the project, I'll just merge the fix. Thanks.

**Comment by thirtythreeforty** [comment]
:+1: glad I could help!

**Comment by starcraftman** [comment]
@thirtythreeforty Interesting that two refreshes were needed. Thanks for fixing upstream, now I can remove my own little hack.

**Pull request merged**
